using System.Text;
using NVS.Core.Models;

namespace NVS.Services.Containers;

/// <summary>
/// Generates multistage Dockerfiles for .NET projects and docker-compose files
/// for solutions. Pure string builders — fully unit-testable.
/// </summary>
public static class DockerfileScaffolder
{
    /// <summary>Maps a TargetFramework moniker (e.g. "net10.0") to the image tag ("10.0").</summary>
    public static string FrameworkVersion(string targetFramework)
    {
        // net10.0 → 10.0, net9.0 → 9.0, net8.0 → 8.0, net48 → 4.8 (unsupported for linux images, caller beware)
        if (targetFramework.StartsWith("net", StringComparison.OrdinalIgnoreCase) && targetFramework.Length > 3)
        {
            return targetFramework[3..];
        }
        return "10.0";
    }

    /// <summary>
    /// Generates a multistage Dockerfile for a .NET project: SDK build → publish → slim
    /// runtime image. Web projects get the aspnet base + EXPOSE 8080; executables get an
    /// ENTRYPOINT; libraries produce a build-artifacts image with no entrypoint.
    /// </summary>
    public static string GenerateDotNetDockerfile(ProjectModel project)
    {
        var version = FrameworkVersion(project.TargetFramework);
        var projectFileName = Path.GetFileName(project.FilePath);
        var assemblyName = project.AssemblyName ?? project.Name;
        var isWeb = project.IsWebProject;
        var isExe = project.IsExecutable;

        var sb = new StringBuilder();
        sb.AppendLine($"# Dockerfile for {project.Name} — generated by NVS");
        sb.AppendLine($"# Build:  docker build -t {project.Name.ToLowerInvariant()} .");
        sb.AppendLine($"# Run:    docker run --rm -p 8080:8080 {project.Name.ToLowerInvariant()}");
        sb.AppendLine();

        sb.AppendLine($"FROM mcr.microsoft.com/dotnet/sdk:{version} AS build");
        sb.AppendLine("WORKDIR /src");
        sb.AppendLine($"COPY \"{projectFileName}\" .");
        sb.AppendLine($"RUN dotnet restore \"{projectFileName}\"");
        sb.AppendLine("COPY . .");
        sb.AppendLine($"RUN dotnet publish \"{projectFileName}\" -c Release -o /app/publish --no-restore");
        sb.AppendLine();

        if (isWeb)
        {
            sb.AppendLine($"FROM mcr.microsoft.com/dotnet/aspnet:{version} AS final");
        }
        else if (isExe)
        {
            sb.AppendLine($"FROM mcr.microsoft.com/dotnet/runtime:{version} AS final");
        }
        else
        {
            sb.AppendLine($"FROM mcr.microsoft.com/dotnet/runtime:{version} AS final");
            sb.AppendLine("# NOTE: library project — the image contains build output but has no entrypoint.");
        }

        sb.AppendLine("WORKDIR /app");
        sb.AppendLine("COPY --from=build /app/publish .");

        if (isWeb)
        {
            sb.AppendLine("EXPOSE 8080");
        }

        if (isExe)
        {
            sb.AppendLine($"ENTRYPOINT [\"dotnet\", \"{assemblyName}.dll\"]");
        }
        else
        {
            sb.AppendLine("# ENTRYPOINT intentionally omitted — not a runnable application.");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generates a docker-compose file with one service per executable project in the
    /// solution. <paramref name="solutionDirectory"/> anchors relative build contexts.
    /// </summary>
    public static string GenerateCompose(string solutionName, string solutionDirectory, IReadOnlyList<ProjectModel> projects)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# docker-compose for {solutionName} — generated by NVS");
        sb.AppendLine($"# Up:   docker compose -f docker-compose.yml up -d --build");
        sb.AppendLine($"# Down: docker compose -f docker-compose.yml down");
        sb.AppendLine();
        sb.AppendLine("services:");

        var executableProjects = projects.Where(p => p.IsExecutable).ToList();
        foreach (var project in executableProjects)
        {
            var serviceName = project.Name.ToLowerInvariant().Replace(' ', '-').Replace('_', '-');
            var projectDir = Path.GetDirectoryName(project.FilePath) ?? ".";
            var relativeContext = Path.GetRelativePath(solutionDirectory, projectDir);
            if (string.IsNullOrEmpty(relativeContext)) relativeContext = ".";

            sb.AppendLine($"  {serviceName}:");
            sb.AppendLine($"    build:");
            sb.AppendLine($"      context: {relativeContext.Replace('\\', '/')}");
            sb.AppendLine($"      dockerfile: Dockerfile");
            sb.AppendLine($"    image: {serviceName}:latest");
            sb.AppendLine($"    container_name: {serviceName}");

            if (project.IsWebProject)
            {
                sb.AppendLine("    ports:");
                sb.AppendLine("      - \"8080:8080\"");
            }

            sb.AppendLine("    restart: unless-stopped");
        }

        if (executableProjects.Count == 0)
        {
            sb.AppendLine($"  # No executable projects found in {solutionName}.");
            sb.AppendLine($"  # Add a runnable project (OutputType=Exe or a web SDK) and regenerate.");
        }

        return sb.ToString();
    }
}
